### ISSUE TITLE
Include German Language Context

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofft-web-client#48]
_**This is a post launch fix and should not inhibit the launch of the site.**_ 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the issue is. Ex. I'm always frustrated when [...]
- lofft.app info page currently is only in English, the German language version should be created. 

**Describe the solution you'd like**
- ReactJS has a package that can handle this and should be implemented.

**To Do**
- [x] Write a EN file
- [ ] #59

**Additional context**

**Comment by valentinLW** [comment]
I created a DE file issue, we need to merge this without the finished translation so i can work on issue #56
